#!/usr/bin/env /usr/bin/python3.6
import sys
import psutil
import os
import signal

option = sys.argv[1]

def main():

	if option == "start":
		print("Starting manager ...")
		os.chdir("/aux0/customer/containers/occonfman/")
		os.system("/usr/bin/python3.6 manager.py >/dev/null &")
	elif option == "stop":
		pstring = "manager.py"
		for line in os.popen("ps ax | grep " + pstring + " | grep -v grep"):
			fields = line.split()
			pid = fields[0]
		print("Stopping manager ...")
		os.kill(int(pid), signal.SIGKILL)
	else:
		print("Usage of manager : ")
		print("manager start/stop")

main()